configs = {
    "date": "2022-1-20",
    "__COMMENT__1": "Date format is yyyy-m-d. Change the date accordingly",
    "__COMMENT__2": "Date cannot be more than 1 week as we are using standard Twitter developer accounts."
                    "We cannot crawl tweets older than one week",
    "covid": {
        '__COMMENT__': 'To collect Covid data concat of offensive_words and Covid_words(1 to 4) were used in this way '
                       'search_term = "("+ offensive_words +")" + " and " +  "("+ Covid_words1+")',
        'topic_keywords': "vaccineskill "
                          "OR forcedinjections "
                          "OR b1less "
                          "OR vaccinescauseautism "
                          "OR NoMasks "
                          "OR ConstitutionOverCoronavirus "
                          "OR syringeslaughter "
                          "OR biologicallyengineeredhumans "
                          "OR antivaccine "
                          "OR bewaretheneedle "
                          "OR idiotsguidetovaccines "
                          "OR pharmaceuticalskill "
                          "OR antivax ",
        'topic_keyowrds2': "vaccinedeath "
                           "OR byebyebigpharma "
                           "OR populationcontrol "
                           "OR geoengineering "
                           "OR medicalfreedom "
                           "OR antivaxer "
                           "OR vaccineinjury "
                           "OR vaccinesharm "
                           "OR alternativemedicine "
                           "OR antivaxxers "
                           "OR vaccineinjuryawareness "
                           "OR antivaxx ",
        "topic_keywords3": "anti-vaxxers "
                           "OR anti-vaxx "
                           "OR Gatesgohome "
                           "OR healthfreedom "
                           "OR vaccinviolate "
                           "OR vaccinesavage "
                           "OR vaccineterror "
                           "OR novaccine "
                           "OR notvaccine "
                           "OR vaccinehurt "
                           "OR vaccineviolate "
                           "OR wildvaccine "
                           "OR brutalvaccine "
                           "OR vax "
                           "OR vaxxed "
                           "OR vaxxer ",
        "topic_keywords4": "barbaricvaccine "
                           "OR microchip "
                           "OR covid "
                           "OR controlsensors "
                           "OR forcedvaccin "
                           "OR vaccinecancer "
                           "OR reptilianinjection "
                           "OR vaccinetyranny "
                           "OR injusticevaccine "
                           "OR tuskegeevaccine "
                           "OR tuskegeestudy "
                           "OR vaccinepoison "
                           "OR vaccinemisuse ",
        'hate_keywords': "bitch "
                         "OR savage "
                         "OR fuck "
                         "OR slut "
                         "OR fucker "
                         "OR dickhead "
                         "OR suckit "
                         "OR suckmydick "
                         "OR pussyboy "
                         "OR fagot "
                         "OR idiot "
                         "OR shit ",
        "hashtags_keywords": "#Jihadivirus "
                             "OR #chinesevirus "
                             "OR #bateater "
                             "OR #dogeater "
    },
    "trump": {
        '__COMMENT__': 'Trump related keywords used jointly',
        'hate_keywords': "#bitch "
                         "OR fake pandemic "
                         "OR slut "
                         "OR #blm "
                         "OR feminismcancer "
                         "OR feminismterrorism "
                         "OR #killblacks "
                         "OR #fucktrump "
                         "OR #fuckblm "
                         "OR #trumbitch "
                         "OR #trumpgays "
                         "OR #killlgbt "
                         "OR #murdergays "
                         "OR gay "
                         "OR lgbt "
                         "OR allahsoil "
                         "OR protest "
                         "OR muslim "
                         "OR nazi "
                         "OR antiamerican ",
        'topic_keywords': "Trump "
                          "OR #trump "
                          "OR #notmypresident "
                          "OR #election2020 "
                          "OR #donaldtrump "
                          "OR #liberals "
    }
}
